# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
pygments: true
markdown: kramdown

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Jekyll for Android

description: Stylish Jekyll Theme
author:
  name: Jekyll for Android
  email: tsagiotis@gmail.com
  github: tsagi/jekyll-client-for-android
  twitter:
  pinterest:
  linkedin:
  bio: A Jekyll client for Android.
  email_md5:

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH: /jekyll-client-for-android
